# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_NPY=111  CONDA_PY=27
    - CONDA_NPY=112  CONDA_PY=27
    - CONDA_NPY=111  CONDA_PY=35
    - CONDA_NPY=112  CONDA_PY=35
    - CONDA_NPY=111  CONDA_PY=36
    - CONDA_NPY=112  CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "GVdBxBezxVEXrmVrfpnIpkTn1Y58GGXg3UaOxT7nkQoQ4OfmVmbq1rIFVqWqd3Qija86gKupyBp0RI4mFuZhhs2F9/hBZwC+0pAHH4nvkE51lT2J19XPbn/OgIrmkb1bex/YlWC0cqWHAPRKTn1vsyDQ7uJ7cZjDe2W2OFLGjkfeEPQj1IqclRr8RzOE4mOwB3Zx+m4M7pJoQWUxmUp25EChTayxb26vkGmyFR4PtczDsf+uNwjNkYmLXeYvXHmxRc/0MmqmoFjTD+V24xa3S5sHTe8hz3q0E8DE+S96p/ckBysTlwj5yO6l40MLAM2C7uWteJi6BuUNA9/h64CB+4dhEW7lnG0wtH3bIODUqfforneldSB0d52INTrcB5ANdNLtGJtosyy5VObprAw9LgQcVpEPS2GD2dDUAF6+O9wDSWc5dmQyCZnykzUZTvw0RnOJicvBRnA3QkyRvDJ+J6YkoUfwW06FyAYy4kw2K/xBM4lBLhnewCF1yPhmGPgU5DixU5Znmk3V5eZ80kAPtH4yH+iDMHK74kxFalJRDYWju6CRRbLY/be2yhO8cyQBiqeQaC6AtM0/FezyW2Eh9jLRLfGIeV0zRF7KKA3f9O++OnXUvYUx86gSLqXlr2wKu24GODhrgITUCee3+cEj70m6+Yk7HioxIeTvelktm6E="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
